# report generation.db logdb.txt
#.db logdb.txt
# ./report.sh UoMMontChoisy.db logdb.txt
# ./report.sh UOMMapou.db logdb.txt
# ./report.sh UOMLongMountain.db logdb.txt
# ./report.sh hotel_airport.db logdb.txt
# ./report.sh survey2.db logdb.txt
# ./report.sh univ_hotel.db logdb.txt
# ./report.sh Quatre_Bornes.db logdb.txt
# ./report.sh vallee_des_pretres.db logdb.txt
# ./report.sh ntsaweni_maweni.db logdb.txt
# ./report.sh com_tel_hahaya_methahaya.db logdb.txt
# ./report.sh "bahani_hahaya_(1).db" logdb.txt
# ./report.sh mtfinance_anacm_metoffice1.db logdb.txt
# ./report.sh toima_tel_anrt.db logdb.txt
# ./report.sh itsoundzou_coimbani.db logdb.txt
# ./report.sh bahani_hahaya.db logdb.txt
# ./report.sh tsoudjini_bahani.db logdb.txt
# ./report.sh toima_tel.db logdb.txt
# ./report.sh metoffice1_to_met2.db logdb.txt
# ./report.sh meteo_moroni1_office.db logdb.txt
# ./report.sh survey_1.db logdb.txt
# ./report.sh survey_2.db logdb.txt
# ./report.sh survey_3.db logdb.txt
./report.sh gatden-h.db logdb.txt
./report.sh gatden-h_0.db logdb.txt
# ./report.sh hotel_univ.db logdb.txt
# ./report.sh univ_hotel_0.db logdb.txt
# ./report.sh UoL_Monrovia_2.db logdb.txt
# ./report.sh Mamba_Point_Monrovia.db logdb.txt
# ./report.sh test.db logdb.txt
# ./report.sh test2.db logdb.txt
# ./report.sh vacoas1.db logdb.txt
# ./report.sh Vacoas_Test.db logdb.txt
# ./report.sh UoL_Monrovia.db logdb.txt
# ./report.sh Monrovia1.db logdb.txt
# ./report.sh pro.db logdb.txt
# ./report.sh chefcha.db logdb.txt
# ./report.sh chef_cha.db logdb.txt
# ./report.sh vallecas.db logdb.txt
# ./report.sh valleccas.db logdb.txt
# ./report.sh chefchaouen.db logdb.txt
# ./report.sh fes_to_chef_6.db logdb.txt
# ./report.sh fes_to_chef_5.db logdb.txt
# ./report.sh fez_to_chef_4.db logdb.txt
# ./report.sh fes_to_chef_3_.db logdb.txt
# ./report.sh fez_tonchefchahuen_2.db logdb.txt
# ./report.sh fez_to_chefchahuen.db logdb.txt
# ./report.sh test_steve.db logdb.txt
# ./report.sh mozambyy15.db logdb.txt
# ./report.sh mozambyy.db logdb.txt
